export const Types = {
    ADD_TODO: 'ADD_TODO',
    MODIFY_TODO: 'MODIFY_TODO',
    DELETE_TODO: 'DELETE_TODO',
    TOGGLE_TODO:'TOGGLE_TODO',
    UPDATE_FILTER:'UPDATE_FILTER',
    GET_ONLINE_TODO:'GET_ONLINE_TODO',
    SUCCESS_ACTION:'SUCCESS_ACTION',
    LOADING_ACTION:'SUCCESS_ACTION',
    ERROR_ACTION:'SUCCESS_ACTION'
  };